name: InProvLife
favicon: null
layout_spectrum: 0.36313
typography_spectrum: 0.14182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0ceda'
    - '#131313'
    - '#009b74'
    - '#6e83a2'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
